language: python

python:
  - "3.6"

cache:
  - pip
  directories:
    -s "$HOME/coding/google-cloud-sdk"pip

install:
  - pip install -r ./api/requirements.txt

script:
  - echo "Implement tests"

deplpy:
  # todo: Implement
