apiVersion: v1
kind: Service
metadata:
  namespace: api
  labels:
    app: elt-smartsheets
  name: elt-smartsheets
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: elt-smartsheets